import type { LucideIcon } from "lucide-react";
import {
  Footprints,
  Sparkles,
  TrendingUp,
  Coins,
  Gem,
  Mountain,
  PartyPopper,
  Crown,
  ClipboardList,
  FlaskConical,
  CalendarDays,
  LayoutDashboard,
  Hash,
  Flame,
  CalendarRange,
  Trophy,
  Target,
  Banknote,
  Hammer,
  CircleDot,
  Scale,
  CreditCard,
  Landmark,
  Zap,
  Snowflake,
  Gauge,
  Brain,
  RotateCcw,
  HeartHandshake,
  Timer,
  Medal,
  Sparkle,
} from "lucide-react";
import type { AchievementCatalogEntry, MilestoneTier, WinsSection } from "./types";
import type { AchievementCtx } from "./context";

const LOAN_TYPES = new Set([
  "Personal Loan",
  "Auto Loan",
  "Student Loan",
  "Mortgage",
]);

function entry(
  id: string,
  section: WinsSection,
  tier: MilestoneTier,
  title: string,
  subtitle: string,
  lockedHint: string,
  gridLockedLabel: string,
  Icon: LucideIcon,
  check: (c: AchievementCtx) => boolean,
): AchievementCatalogEntry {
  return { id, section, tier, title, subtitle, lockedHint, gridLockedLabel, Icon, check };
}

function clearedDebts(c: AchievementCtx) {
  return c.debts.filter((d) => d.balance <= 0.01);
}

function smallestCleared(c: AchievementCtx): boolean {
  if (c.debtsCleared < 1 || c.debts.length === 0) return false;
  const minAll = Math.min(...c.debts.map((d) => d.initialBalance));
  return clearedDebts(c).some((d) => Math.abs(d.initialBalance - minAll) < 0.01);
}

function largestCleared(c: AchievementCtx): boolean {
  if (c.debtsCleared < 1 || c.debts.length === 0) return false;
  const maxAll = Math.max(...c.debts.map((d) => d.initialBalance));
  return clearedDebts(c).some((d) => Math.abs(d.initialBalance - maxAll) < 0.01);
}

function highestAprCleared(c: AchievementCtx): boolean {
  const cl = clearedDebts(c);
  if (cl.length === 0) return false;
  const maxRate = Math.max(...cl.map((d) => d.interestRate));
  return cl.some((d) => d.interestRate >= maxRate - 0.0001);
}

export const WINS_SECTION_ORDER: WinsSection[] = [
  "getting-started",
  "building-momentum",
  "progress-milestones",
  "money-milestones",
  "debt-knockout",
  "smart-behavior",
  "comeback",
  "major-milestones",
  "debt-free",
];

export const WINS_SECTION_TITLE: Record<WinsSection, string> = {
  "getting-started": "Getting Started",
  "building-momentum": "Momentum",
  "progress-milestones": "Progress",
  "money-milestones": "Payments milestone",
  "debt-knockout": "Debt knockout",
  "smart-behavior": "Smart moves",
  "comeback": "Consistency & comeback",
  "major-milestones": "Major milestones",
  "debt-free": "Debt-Free",
};

const pctIcon = TrendingUp;
const moneyIcon = Banknote;

function pctBadge(
  id: string,
  minPct: number,
  title: string,
  section: WinsSection,
  tier: MilestoneTier,
): AchievementCatalogEntry {
  return entry(
    id,
    section,
    tier,
    title,
    `Pay down ${minPct}% of your starting balances.`,
    `Reach ${minPct}% paid off across your debts.`,
    "Keep stacking payments",
    pctIcon,
    (c) => c.totalInitial > 0 && c.pctPaid >= minPct - 0.0001,
  );
}

function moneyBadge(
  id: string,
  min: number,
  title: string,
  tier: MilestoneTier,
): AchievementCatalogEntry {
  return entry(
    id,
    "money-milestones",
    tier,
    title,
    "Lifetime payments logged in Zeni.",
    `Log ${formatUsdTitle(min)} in total payments.`,
    "Keep stacking payments",
    moneyIcon,
    (c) => c.totalPaid >= min - 0.009,
  );
}

function formatUsdTitle(n: number): string {
  if (n >= 1000) return `$${(n / 1000).toLocaleString(undefined, { maximumFractionDigits: n % 1000 === 0 ? 0 : 1 })}k`;
  return `$${n}`;
}

export const ACHIEVEMENT_CATALOG: AchievementCatalogEntry[] = [
  entry(
    "first-debt",
    "getting-started",
    "small",
    "First debt tracked",
    "You showed up — that’s the hardest part.",
    "Add your first debt to unlock this badge.",
    "Add a debt to start",
    Footprints,
    (c) => c.debtCount >= 1,
  ),
  entry(
    "first-payment",
    "getting-started",
    "small",
    "First payment logged",
    "Momentum beats perfection.",
    "Log a payment to unlock.",
    "Log your first payment",
    Sparkles,
    (c) => c.paymentCount >= 1,
  ),
  entry(
    "first-plan",
    "getting-started",
    "small",
    "First plan created",
    "You opened your payoff plan.",
    "Visit Plan with at least one debt.",
    "Open your plan",
    ClipboardList,
    (c) => c.signals.planViewed && c.debtCount >= 1,
  ),
  entry(
    "first-whatif",
    "getting-started",
    "small",
    "First “what-if” run",
    "You stress-tested the future.",
    "Open the What if simulator once.",
    "Try the simulator",
    FlaskConical,
    (c) => c.signals.simRuns >= 1,
  ),
  entry(
    "two-weeks-active",
    "getting-started",
    "small",
    "Two weeks of action",
    "Payments in more than one week.",
    "Log payments across two different weeks.",
    "Log in another week",
    CalendarDays,
    (c) => c.distinctPaymentWeeks >= 2,
  ),
  entry(
    "dash-streak-3",
    "getting-started",
    "small",
    "3-day dashboard streak",
    "You kept checking in.",
    "Open the dashboard three days in a row.",
    "Visit three days straight",
    LayoutDashboard,
    (c) => c.dashboardDayStreakMax >= 3,
  ),

  entry(
    "pay-3",
    "building-momentum",
    "small",
    "3 payments logged",
    "Consistency is showing.",
    "Log three payments.",
    "Log three payments",
    Hash,
    (c) => c.paymentCount >= 3,
  ),
  entry(
    "pay-5",
    "building-momentum",
    "small",
    "5 payments logged",
    "You’re building rhythm.",
    "Log five payments.",
    "Log five payments",
    Hash,
    (c) => c.paymentCount >= 5,
  ),
  entry(
    "pay-10",
    "building-momentum",
    "big",
    "10 payments logged",
    "Double digits of proof.",
    "Log ten payments.",
    "Log ten payments",
    Hash,
    (c) => c.paymentCount >= 10,
  ),
  entry(
    "streak-7",
    "building-momentum",
    "big",
    "7-day payment streak",
    "A full week of forward motion.",
    "Log at least one payment on seven consecutive calendar days.",
    "Pay at least daily for a week",
    Flame,
    (c) => c.maxPaymentDayStreak >= 7,
  ),
  entry(
    "streak-14",
    "building-momentum",
    "big",
    "14-day payment streak",
    "Two relentless weeks.",
    "Keep daily payment activity for 14 days.",
    "Build a longer streak",
    Flame,
    (c) => c.maxPaymentDayStreak >= 14,
  ),
  entry(
    "streak-30",
    "building-momentum",
    "major",
    "30-day payment streak",
    "A month of discipline.",
    "Hit 30 consecutive days with payments logged.",
    "Keep the streak alive",
    Flame,
    (c) => c.maxPaymentDayStreak >= 30,
  ),
  entry(
    "weeks-3-row",
    "building-momentum",
    "big",
    "3-week payment rhythm",
    "Three straight weeks with payments.",
    "Log a payment in three consecutive calendar weeks.",
    "Stack three weeks",
    CalendarRange,
    (c) => c.consecutiveWeeksWithPayment >= 3,
  ),
  entry(
    "weeks-4-row",
    "building-momentum",
    "big",
    "4-week payment rhythm",
    "A month of weekly wins.",
    "Log a payment in four consecutive calendar weeks.",
    "Stack four weeks",
    CalendarRange,
    (c) => c.consecutiveWeeksWithPayment >= 4,
  ),
  entry(
    "beat-best-week",
    "building-momentum",
    "big",
    "Beat your best week",
    "New weekly high.",
    "Outdo your prior best week’s payments.",
    "Top your weekly record",
    Trophy,
    (c) => c.eng.newWeekBest,
  ),
  entry(
    "beat-best-month",
    "building-momentum",
    "big",
    "Beat your best month",
    "Monthly record shattered.",
    "Outdo your prior best month’s payments.",
    "Top your monthly record",
    Trophy,
    (c) => c.eng.newMonthBest,
  ),

  pctBadge("pct-5", 5, "5% cleared", "progress-milestones", "small"),
  entry(
    "10pct",
    "progress-milestones",
    "small",
    "10% cleared",
    "The snowball is rolling.",
    "Pay down 10% of your total balances.",
    "Keep stacking payments",
    TrendingUp,
    (c) => c.totalInitial > 0 && c.pctPaid >= 10 - 0.0001,
  ),
  pctBadge("pct-15", 15, "15% cleared", "progress-milestones", "small"),
  pctBadge("pct-25", 25, "25% cleared", "progress-milestones", "small"),
  pctBadge("pct-35", 35, "35% cleared", "progress-milestones", "small"),
  entry(
    "halfway",
    "major-milestones",
    "big",
    "Halfway there",
    "More behind you than ahead.",
    "Pay down 50% of your balances.",
    "Pay down 50%",
    Mountain,
    (c) => c.totalInitial > 0 && c.pctPaid >= 50 - 0.0001,
  ),
  pctBadge("pct-60", 60, "60% cleared", "progress-milestones", "big"),
  pctBadge("pct-75", 75, "75% cleared", "major-milestones", "big"),
  pctBadge("pct-85", 85, "85% cleared", "progress-milestones", "big"),
  pctBadge("pct-90", 90, "90% cleared", "major-milestones", "big"),
  pctBadge("pct-95", 95, "95% cleared", "progress-milestones", "major"),

  moneyBadge("paid-100", 100, "$100 paid", "small"),
  moneyBadge("paid-250", 250, "$250 paid", "small"),
  entry(
    "500-paid",
    "money-milestones",
    "big",
    "$500 paid",
    "A serious chunk carved off.",
    "Lifetime payments hit $500.",
    "Keep stacking payments",
    Coins,
    (c) => c.totalPaid >= 500 - 0.009,
  ),
  moneyBadge("paid-750", 750, "$750 paid", "small"),
  entry(
    "1k-paid",
    "money-milestones",
    "big",
    "$1,000 paid",
    "Four figures of proof.",
    "Reach $1,000 in total payments.",
    "Keep stacking payments",
    Gem,
    (c) => c.totalPaid >= 1000 - 0.009,
  ),
  moneyBadge("paid-2500", 2500, "$2,500 paid", "big"),
  moneyBadge("paid-5000", 5000, "$5,000 paid", "big"),
  moneyBadge("paid-7500", 7500, "$7,500 paid", "big"),
  moneyBadge("paid-10000", 10000, "$10,000 paid", "major"),
  moneyBadge("paid-15000", 15000, "$15,000 paid", "major"),
  moneyBadge("paid-25000", 25000, "$25,000 paid", "major"),
  moneyBadge("paid-50000", 50000, "$50,000 paid", "major"),

  entry(
    "first-clear",
    "debt-knockout",
    "major",
    "First debt destroyed",
    "One account at zero.",
    "Pay off a debt completely.",
    "Pay off one debt",
    PartyPopper,
    (c) => c.debtsCleared >= 1,
  ),
  entry(
    "cleared-2",
    "debt-knockout",
    "big",
    "2 debts destroyed",
    "Two down — more to go.",
    "Pay off two debts completely.",
    "Clear another debt",
    Hammer,
    (c) => c.debtsCleared >= 2,
  ),
  entry(
    "cleared-3",
    "debt-knockout",
    "big",
    "3 debts destroyed",
    "Triple knockout.",
    "Pay off three debts completely.",
    "Clear more debts",
    Hammer,
    (c) => c.debtsCleared >= 3,
  ),
  entry(
    "cleared-5",
    "debt-knockout",
    "major",
    "5 debts destroyed",
    "Half a dozen victories.",
    "Pay off five debts completely.",
    "Clear five debts",
    Hammer,
    (c) => c.debtsCleared >= 5,
  ),
  entry(
    "smallest-down",
    "debt-knockout",
    "big",
    "Smallest balance cleared",
    "You crossed off the little guy.",
    "Fully pay off your smallest original balance debt.",
    "Finish your smallest debt",
    CircleDot,
    smallestCleared,
  ),
  entry(
    "largest-down",
    "debt-knockout",
    "major",
    "Largest balance cleared",
    "You took down a giant.",
    "Fully pay off your largest original balance debt.",
    "Finish your biggest debt",
    Scale,
    largestCleared,
  ),
  entry(
    "highest-apr-gone",
    "debt-knockout",
    "major",
    "Highest-rate debt cleared",
    "Interest drag removed.",
    "Pay off your highest APR debt completely.",
    "Clear your priciest rate",
    Gauge,
    highestAprCleared,
  ),
  entry(
    "first-cc-down",
    "debt-knockout",
    "big",
    "First credit card paid off",
    "Plastic at zero.",
    "Pay off a Credit Card debt completely.",
    "Clear a card balance",
    CreditCard,
    (c) => clearedDebts(c).some((d) => d.debtType === "Credit Card"),
  ),
  entry(
    "first-loan-down",
    "debt-knockout",
    "big",
    "First loan paid off",
    "Installment crushed.",
    "Pay off a loan-type debt completely.",
    "Clear a loan",
    Landmark,
    (c) => clearedDebts(c).some((d) => LOAN_TYPES.has(d.debtType)),
  ),

  entry(
    "over-min-once",
    "smart-behavior",
    "small",
    "Above minimum once",
    "Extra went to principal.",
    "Log a payment larger than that debt’s minimum.",
    "Pay a bit over minimum",
    Zap,
    (c) => c.paymentsStrictlyOverMin >= 1,
  ),
  entry(
    "over-min-5",
    "smart-behavior",
    "big",
    "Above minimum ×5",
    "Habit of overpaying.",
    "Log five payments above minimum.",
    "Repeat the habit",
    Zap,
    (c) => c.paymentsStrictlyOverMin >= 5,
  ),
  entry(
    "extra-payment",
    "smart-behavior",
    "small",
    "Extra monthly set",
    "You’re accelerating the plan.",
    "Set extra monthly payoff in Plan.",
    "Add extra monthly",
    Sparkle,
    (c) => c.extraMonthly > 0,
  ),
  entry(
    "use-avalanche",
    "smart-behavior",
    "small",
    "Avalanche engaged",
    "Targeting highest APR first.",
    "Choose avalanche as your strategy.",
    "Switch to avalanche",
    Mountain,
    (c) => c.strategy === "avalanche" && c.debtCount >= 1,
  ),
  entry(
    "use-snowball",
    "smart-behavior",
    "small",
    "Snowball engaged",
    "Smallest balance first.",
    "Choose snowball as your strategy.",
    "Switch to snowball",
    Snowflake,
    (c) => c.strategy === "snowball" && c.debtCount >= 1,
  ),
  entry(
    "dash-7",
    "smart-behavior",
    "big",
    "7-day dashboard streak",
    "You stayed close to the numbers.",
    "Open the dashboard seven days in a row.",
    "Check in daily",
    LayoutDashboard,
    (c) => c.dashboardDayStreakMax >= 7,
  ),
  entry(
    "whatif-3",
    "smart-behavior",
    "small",
    "What-if ×3",
    "You explored the future.",
    "Open the simulator three times.",
    "Run more scenarios",
    Brain,
    (c) => c.signals.simRuns >= 3,
  ),

  entry(
    "returned-7",
    "comeback",
    "small",
    "Back after a week away",
    "You didn’t quit — you returned.",
    "Log a payment after 7+ days without one.",
    "Come back and pay",
    RotateCcw,
    (c) => c.returnedAfter7,
  ),
  entry(
    "returned-30",
    "comeback",
    "big",
    "Back after 30 days away",
    "Long pause, stronger return.",
    "Log a payment after 30+ days without one.",
    "Return and restart",
    RotateCcw,
    (c) => c.returnedAfter30,
  ),
  entry(
    "after-gap-pay",
    "comeback",
    "small",
    "Payment after a long gap",
    "Momentum restored.",
    "Log a payment after 14+ days without one.",
    "Break the silence",
    HeartHandshake,
    (c) => c.loggedAfterGap14,
  ),
  entry(
    "consistent-60",
    "comeback",
    "major",
    "60-day payment consistency",
    "Two months of showing up.",
    "Maintain a 60-day streak of days with payments.",
    "Keep the streak",
    Timer,
    (c) => c.maxPaymentDayStreak >= 60,
  ),
  entry(
    "consistent-90",
    "comeback",
    "major",
    "90-day payment consistency",
    "A quarter of discipline.",
    "Maintain a 90-day streak of days with payments.",
    "Keep going",
    Timer,
    (c) => c.maxPaymentDayStreak >= 90,
  ),

  entry(
    "almost-free",
    "debt-free",
    "big",
    "Almost debt-free",
    "You can see the finish line.",
    "Reach 90–95% paid off while still carrying a balance.",
    "Close the gap",
    Target,
    (c) =>
      c.totalInitial > 0 &&
      !c.allClear &&
      c.pctPaid >= 90 - 0.0001 &&
      c.pctPaid < 95 - 0.0001,
  ),
  entry(
    "all-clear",
    "debt-free",
    "major",
    "Debt-free",
    "You rewrote your financial story.",
    "Zero every balance.",
    "Reach zero balance",
    Crown,
    (c) => c.allClear,
  ),
  entry(
    "debt-free-30",
    "debt-free",
    "major",
    "30 days debt-free",
    "A full month in the clear.",
    "Stay all-clear for 30 days.",
    "Keep balances at zero",
    Medal,
    (c) => c.allClear && c.daysDebtFree != null && c.daysDebtFree >= 30,
  ),
  entry(
    "debt-free-90",
    "debt-free",
    "major",
    "90 days debt-free",
    "Freedom is becoming normal.",
    "Stay all-clear for 90 days.",
    "Protect your zeroes",
    Medal,
    (c) => c.allClear && c.daysDebtFree != null && c.daysDebtFree >= 90,
  ),
];

export const MILESTONE_SYNC_DEFS = ACHIEVEMENT_CATALOG.map((a) => ({
  key: a.id,
  check: a.check,
}));
